// https://api.yelp.com/v3/businesses/search?location=95742&radius=39999&categories=beergardens&sort_by=rating

const beerGardensData = [
  {
    id: "7eyOUHlgLiXfUyNcqqwx2w",
    alias: "sacyard-community-tap-house-sacramento-2",
    name: "SacYard Community Tap House",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/rVgHisbTU5EJHLz4-rrIDA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/sacyard-community-tap-house-sacramento-2?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 207,
    categories: [
      {
        alias: "beerbar",
        title: "Beer Bar",
      },
      {
        alias: "beergardens",
        title: "Beer Gardens",
      },
      {
        alias: "foodtrucks",
        title: "Food Trucks",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.5642675099592,
      longitude: -121.465629972517,
    },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "1725 33rd St",
      address2: "",
      address3: null,
      city: "Sacramento",
      zip_code: "95816",
      country: "US",
      state: "CA",
      display_address: ["1725 33rd St", "Sacramento, CA 95816"],
    },
    phone: "+19164004708",
    display_phone: "(916) 400-4708",
    distance: 22412.58299921581,
  },
  {
    id: "eLLTke9xBze6rCbv8sEvVA",
    alias: "midtown-biergarten-sacramento",
    name: "Midtown BierGarten",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/Ig_PjgIsJTBj3LCFtsMevA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/midtown-biergarten-sacramento?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 437,
    categories: [
      {
        alias: "german",
        title: "German",
      },
      {
        alias: "beergardens",
        title: "Beer Gardens",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.5742593,
      longitude: -121.4758834,
    },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "2332 K St",
      address2: "",
      address3: "",
      city: "Sacramento",
      zip_code: "95816",
      country: "US",
      state: "CA",
      display_address: ["2332 K St", "Sacramento, CA 95816"],
    },
    phone: "+19163464572",
    display_phone: "(916) 346-4572",
    distance: 23236.31348739376,
  },
  {
    id: "VMzhYtUaeBswzmhCZzyF3Q",
    alias: "hop-gardens-taproom-sacramento",
    name: "Hop Gardens Taproom",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/0iQyeMb_llqtvXayH0mzxA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/hop-gardens-taproom-sacramento?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 198,
    categories: [
      {
        alias: "beergardens",
        title: "Beer Gardens",
      },
      {
        alias: "beerbar",
        title: "Beer Bar",
      },
      {
        alias: "pizza",
        title: "Pizza",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.55184,
      longitude: -121.47619,
    },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "2904 Franklin Blvd",
      address2: "",
      address3: null,
      city: "Sacramento",
      zip_code: "95818",
      country: "US",
      state: "CA",
      display_address: ["2904 Franklin Blvd", "Sacramento, CA 95818"],
    },
    phone: "+19164763889",
    display_phone: "(916) 476-3889",
    distance: 23419.71047412507,
  },
  {
    id: "cSu72agWaW4cT-YqtrubSw",
    alias: "kathrins-biergarten-rocklin",
    name: "Kathrin's Biergarten",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/yEVCu_lwoGqQ4KR0ImGVTg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/kathrins-biergarten-rocklin?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 525,
    categories: [
      {
        alias: "german",
        title: "German",
      },
      {
        alias: "beergardens",
        title: "Beer Gardens",
      },
      {
        alias: "brewpubs",
        title: "Brewpubs",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 38.7906899105099,
      longitude: -121.224365,
    },
    transactions: ["delivery"],
    price: "$$",
    location: {
      address1: "4810 Granite Dr",
      address2: "Ste 1A",
      address3: null,
      city: "Rocklin",
      zip_code: "95677",
      country: "US",
      state: "CA",
      display_address: ["4810 Granite Dr", "Ste 1A", "Rocklin, CA 95677"],
    },
    phone: "+19162517502",
    display_phone: "(916) 251-7502",
    distance: 24327.15002034942,
  },
  {
    id: "AIbg4x_afPk4G70DGSm0nw",
    alias: "concerts-in-the-park-sacramento-3",
    name: "Concerts In the Park",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/VvkAKrTNYGi7sobjxomHxg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/concerts-in-the-park-sacramento-3?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 28,
    categories: [
      {
        alias: "foodtrucks",
        title: "Food Trucks",
      },
      {
        alias: "musicvenues",
        title: "Music Venues",
      },
      {
        alias: "beergardens",
        title: "Beer Gardens",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.5810067012858,
      longitude: -121.493903075768,
    },
    transactions: [],
    price: "$",
    location: {
      address1: "901 I St",
      address2: "",
      address3: "Cesar Chavez Plaza",
      city: "Sacramento",
      zip_code: "95814",
      country: "US",
      state: "CA",
      display_address: [
        "901 I St",
        "Cesar Chavez Plaza",
        "Sacramento, CA 95814",
      ],
    },
    phone: "+19168890255",
    display_phone: "(916) 889-0255",
    distance: 24868.938584788764,
  },
  {
    id: "dZQ9jtJsRvGxuWKnSvD1SA",
    alias: "golden-road-brewing-sacramento-2",
    name: "Golden Road Brewing",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/SZyyNLR-Vq2xOJppa1ALMg/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/golden-road-brewing-sacramento-2?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 239,
    categories: [
      {
        alias: "breweries",
        title: "Breweries",
      },
      {
        alias: "beergardens",
        title: "Beer Gardens",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 38.57459,
      longitude: -121.48254,
    },
    transactions: ["delivery", "pickup"],
    price: "$$",
    location: {
      address1: "1830 L St",
      address2: "",
      address3: null,
      city: "Sacramento",
      zip_code: "95811",
      country: "US",
      state: "CA",
      display_address: ["1830 L St", "Sacramento, CA 95811"],
    },
    phone: "+19163829445",
    display_phone: "(916) 382-9445",
    distance: 23863.682091483613,
  },
  {
    id: "kk63V2ym3BuO4IC7vrE0Mg",
    alias: "the-station-public-house-auburn",
    name: "The Station Public House",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/QDM88z3NhFE4MU6bfk5k4Q/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/the-station-public-house-auburn?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 87,
    categories: [
      {
        alias: "beergardens",
        title: "Beer Gardens",
      },
      {
        alias: "gastropubs",
        title: "Gastropubs",
      },
      {
        alias: "wine_bars",
        title: "Wine Bars",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 38.901247,
      longitude: -121.0672129,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "750 Lincoln Way",
      address2: null,
      address3: "",
      city: "Auburn",
      zip_code: "95603",
      country: "US",
      state: "CA",
      display_address: ["750 Lincoln Way", "Auburn, CA 95603"],
    },
    phone: "+15308203353",
    display_phone: "(530) 820-3353",
    distance: 38564.64421739309,
  },
  {
    id: "F5G_utoDBIqDnHs3X3g5fA",
    alias: "back-alley-brewhouse-galt",
    name: "Back Alley Brewhouse",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/9BbwiJ-YyNLgzsP7KgjNlw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/back-alley-brewhouse-galt?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 8,
    categories: [
      {
        alias: "beergardens",
        title: "Beer Gardens",
      },
    ],
    rating: 5.0,
    coordinates: {
      latitude: 38.25305778323588,
      longitude: -121.305664684047,
    },
    transactions: [],
    location: {
      address1: "215 4th St",
      address2: "Ste D",
      address3: null,
      city: "Galt",
      zip_code: "95632",
      country: "US",
      state: "CA",
      display_address: ["215 4th St", "Ste D", "Galt, CA 95632"],
    },
    phone: "+12097306414",
    display_phone: "(209) 730-6414",
    distance: 36500.96917451248,
  },
  {
    id: "RVS2AL2_WbLcDRESzzdblg",
    alias: "the-alley-elk-grove-3",
    name: "The Alley",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/--bVaOE7rS6_tjRR8TUWxw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/the-alley-elk-grove-3?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 101,
    categories: [
      {
        alias: "bowling",
        title: "Bowling",
      },
      {
        alias: "axethrowing",
        title: "Axe Throwing",
      },
      {
        alias: "beergardens",
        title: "Beer Gardens",
      },
    ],
    rating: 3.0,
    coordinates: {
      latitude: 38.42836,
      longitude: -121.464091,
    },
    transactions: [],
    location: {
      address1: "3443 Laguna Blvd",
      address2: "Ste 150",
      address3: "",
      city: "Elk Grove",
      zip_code: "95758",
      country: "US",
      state: "CA",
      display_address: ["3443 Laguna Blvd", "Ste 150", "Elk Grove, CA 95758"],
    },
    phone: "+19162262695",
    display_phone: "(916) 226-2695",
    distance: 27451.944426512055,
  },
  {
    id: "AZpeoBvXCfUTg57G3a46gg",
    alias: "nectar-at-the-villa-taproom-el-dorado-hills",
    name: "Nectar at The Villa - Taproom",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/fkyJKLU0ha0_awHhVdNBcA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/nectar-at-the-villa-taproom-el-dorado-hills?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 3,
    categories: [
      {
        alias: "beergardens",
        title: "Beer Gardens",
      },
    ],
    rating: 5.0,
    coordinates: {
      latitude: 38.657835846949986,
      longitude: -121.0709255,
    },
    transactions: [],
    location: {
      address1: "3905 Park Dr",
      address2: "Ste 100",
      address3: null,
      city: "El Dorado Hills",
      zip_code: "95762",
      country: "US",
      state: "CA",
      display_address: ["3905 Park Dr", "Ste 100", "El Dorado Hills, CA 95762"],
    },
    phone: "",
    display_phone: "",
    distance: 15245.112622715253,
  },
  {
    id: "f3QqbLRE2ddA5MwQMYVbPw",
    alias: "13th-street-porch-sacramento",
    name: "13th Street Porch",
    image_url: "",
    is_closed: false,
    url: "https://www.yelp.com/biz/13th-street-porch-sacramento?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 1,
    categories: [
      {
        alias: "beergardens",
        title: "Beer Gardens",
      },
    ],
    rating: 3.0,
    coordinates: {
      latitude: 38.579894,
      longitude: -121.489476,
    },
    transactions: [],
    location: {
      address1: "13TH St",
      address2: "",
      address3: "Between F & G",
      city: "Sacramento",
      zip_code: "",
      country: "US",
      state: "CA",
      display_address: ["13TH St", "Between F & G", "Sacramento, CA"],
    },
    phone: "",
    display_phone: "",
    distance: 24479.993165905897,
  },
];

module.exports = {
  beerGardensData,
}