export const beerBarsData = [
  {
    id: "fpa4gG1v03afLCxMGg5Ljw",
    alias: "sacramento-pizza-company-folsom",
    name: "Sacramento Pizza Company",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/ZiWxmWLvl3rSoxVjCnaUdw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/sacramento-pizza-company-folsom?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 402,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
      {
        alias: "beerbar",
        title: "Beer Bar",
      },
      {
        alias: "chicken_wings",
        title: "Chicken Wings",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.6570122122873,
      longitude: -121.125263012946,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "2700 E Bidwell St",
      address2: "Ste 500",
      address3: "",
      city: "Folsom",
      zip_code: "95630",
      country: "US",
      state: "CA",
      display_address: ["2700 E Bidwell St", "Ste 500", "Folsom, CA 95630"],
    },
    phone: "+19166739754",
    display_phone: "(916) 673-9754",
    distance: 11852.755282963644,
  },
  {
    id: "xLqBR7u15w6gIb2Rh6kNWg",
    alias: "thai-on-tap-folsom-4",
    name: "Thai on Tap",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/dknuVJkIG-s2RYBr2owwsw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/thai-on-tap-folsom-4?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 185,
    categories: [
      {
        alias: "beerbar",
        title: "Beer Bar",
      },
      {
        alias: "thai",
        title: "Thai",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.65582274570184,
      longitude: -121.17798224540262,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "194 Blue Ravine Rd",
      address2: "Ste 120",
      address3: null,
      city: "Folsom",
      zip_code: "95630",
      country: "US",
      state: "CA",
      display_address: ["194 Blue Ravine Rd", "Ste 120", "Folsom, CA 95630"],
    },
    phone: "+19167908324",
    display_phone: "(916) 790-8324",
    distance: 9649.3835946648,
  },
  {
    id: "sD4AFhqpIz5vtBIjjCw_7A",
    alias: "sushimono-fair-oaks-2",
    name: "Sushimono",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/LGXq_Ti9c0iwfnRngNyCNw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/sushimono-fair-oaks-2?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 634,
    categories: [
      {
        alias: "japanese",
        title: "Japanese",
      },
      {
        alias: "sushi",
        title: "Sushi Bars",
      },
      {
        alias: "beerbar",
        title: "Beer Bar",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 38.663209,
      longitude: -121.272744,
    },
    transactions: ["delivery", "pickup"],
    price: "$$",
    location: {
      address1: "5349 Sunrise Blvd",
      address2: "",
      address3: "",
      city: "Fair Oaks",
      zip_code: "95628",
      country: "US",
      state: "CA",
      display_address: ["5349 Sunrise Blvd", "Fair Oaks, CA 95628"],
    },
    phone: "+19165369885",
    display_phone: "(916) 536-9885",
    distance: 11568.361689007561,
  },
  {
    id: "I1K4zHoQiN-_IwzG5ch3bg",
    alias: "caffe-italiano-ristorante-fair-oaks-2",
    name: "Caffe Italiano Ristorante",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/_dLXrKEP5DjPkUMFK8WT3Q/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/caffe-italiano-ristorante-fair-oaks-2?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 126,
    categories: [
      {
        alias: "italian",
        title: "Italian",
      },
      {
        alias: "salad",
        title: "Salad",
      },
      {
        alias: "beerbar",
        title: "Beer Bar",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.66324333,
      longitude: -121.26126667,
    },
    transactions: ["delivery", "pickup"],
    price: "$$",
    location: {
      address1: "8112 Madison Av",
      address2: null,
      address3: "",
      city: "Fair Oaks",
      zip_code: "95628",
      country: "US",
      state: "CA",
      display_address: ["8112 Madison Av", "Fair Oaks, CA 95628"],
    },
    phone: "+19164364037",
    display_phone: "(916) 436-4037",
    distance: 11123.428288363635,
  },
  {
    id: "-dANAEth6XwSxSOMNoJuqA",
    alias: "sac-brew-bike-sacramento-3",
    name: "Sac Brew Bike",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/7PmLgoeeCWo6aMQbaqvYdA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/sac-brew-bike-sacramento-3?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 290,
    categories: [
      {
        alias: "partybikerentals",
        title: "Party Bike Rentals",
      },
      {
        alias: "beertours",
        title: "Beer Tours",
      },
      {
        alias: "beerbar",
        title: "Beer Bar",
      },
    ],
    rating: 5.0,
    coordinates: {
      latitude: 38.5708179,
      longitude: -121.4837016,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "1519 19th St",
      address2: null,
      address3: "",
      city: "Sacramento",
      zip_code: "95811",
      country: "US",
      state: "CA",
      display_address: ["1519 19th St", "Sacramento, CA 95811"],
    },
    phone: "+19169527973",
    display_phone: "(916) 952-7973",
    distance: 23965.454632211808,
  },
  {
    id: "tbLALCSDRqEakVVn3y18wg",
    alias: "the-backyard-rancho-murieta-2",
    name: "The Backyard",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/3b0afWFTQSmwYtvVTCXaNw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/the-backyard-rancho-murieta-2?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 128,
    categories: [
      {
        alias: "bbq",
        title: "Barbeque",
      },
      {
        alias: "burgers",
        title: "Burgers",
      },
      {
        alias: "beerbar",
        title: "Beer Bar",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 38.49484352006594,
      longitude: -121.10013017593153,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "7238 Murieta Dr",
      address2: "Ste A1",
      address3: null,
      city: "Rancho Murieta",
      zip_code: "95683",
      country: "US",
      state: "CA",
      display_address: [
        "7238 Murieta Dr",
        "Ste A1",
        "Rancho Murieta, CA 95683",
      ],
    },
    phone: "+19163527620",
    display_phone: "(916) 352-7620",
    distance: 12737.422333654647,
  },
  {
    id: "jPhca7oUwnTsIz_SimVzCg",
    alias: "steve-s-pizza-folsom",
    name: "Steve’s Pizza",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/9kw6LR2AgT6zZ7n5E0vRRA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/steve-s-pizza-folsom?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 44,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
      {
        alias: "beerbar",
        title: "Beer Bar",
      },
      {
        alias: "italian",
        title: "Italian",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 38.650906,
      longitude: -121.164862,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "1840 Prairie City Rd",
      address2: "Ste 100",
      address3: "",
      city: "Folsom",
      zip_code: "95630",
      country: "US",
      state: "CA",
      display_address: ["1840 Prairie City Rd", "Ste 100", "Folsom, CA 95630"],
    },
    phone: "+19164611500",
    display_phone: "(916) 461-1500",
    distance: 9528.563423410424,
  },
];
