// https://api.yelp.com/v3/businesses/search?location=95742&radius=39999&categories=beer_and_wine&sort_by=rating

export const bottleShopData = [
  {
    id: "dwZ8c-WzcvpsbKCidWo92g",
    alias: "pacific-market-sacramento",
    name: "Pacific Market",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/yvnDW9ln2GdwNQ8medI-yA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/pacific-market-sacramento?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 76,
    categories: [
      {
        alias: "grocery",
        title: "Grocery",
      },
      {
        alias: "convenience",
        title: "Convenience Stores",
      },
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.5680122375488,
      longitude: -121.475982666016,
    },
    transactions: ["delivery", "pickup"],
    price: "$",
    location: {
      address1: "2500 P St",
      address2: "",
      address3: "",
      city: "Sacramento",
      zip_code: "95816",
      country: "US",
      state: "CA",
      display_address: ["2500 P St", "Sacramento, CA 95816"],
    },
    phone: "+19164564275",
    display_phone: "(916) 456-4275",
    distance: 23299.7899473864,
  },
  {
    id: "FjOrES0z1qG3cBtQdbwcDg",
    alias: "newcastle-pizzeria-newcastle",
    name: "Newcastle Pizzeria",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/FNhX8zhPt6QEuOBE-IkovQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/newcastle-pizzeria-newcastle?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 118,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
      {
        alias: "salad",
        title: "Salad",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.873944324408,
      longitude: -121.133427522924,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "505 Main St",
      address2: "",
      address3: "",
      city: "Newcastle",
      zip_code: "95658",
      country: "US",
      state: "CA",
      display_address: ["505 Main St", "Newcastle, CA 95658"],
    },
    phone: "+19166726263",
    display_phone: "(916) 672-6263",
    distance: 34162.070304123925,
  },
  {
    id: "Gk_HEV3hnpRFxpySQX4CBA",
    alias: "pizzasaurus-rex-sacramento-2",
    name: "Pizzasaurus Rex",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/1UO-sVazfi8nPzIjmI3gMw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/pizzasaurus-rex-sacramento-2?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 270,
    categories: [
      {
        alias: "pizza",
        title: "Pizza",
      },
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.574116,
      longitude: -121.475575,
    },
    transactions: [],
    location: {
      address1: "2322 K St",
      address2: "",
      address3: null,
      city: "Sacramento",
      zip_code: "95816",
      country: "US",
      state: "CA",
      display_address: ["2322 K St", "Sacramento, CA 95816"],
    },
    phone: "+19164765712",
    display_phone: "(916) 476-5712",
    distance: 23259.922752183516,
  },
  {
    id: "xshuOEvM9dpqKSsVHF2soQ",
    alias: "total-wine-and-more-sacramento",
    name: "Total Wine & More",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/d5AM3sBA326cpKBzDHsu6Q/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/total-wine-and-more-sacramento?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 287,
    categories: [
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
      {
        alias: "tobaccoshops",
        title: "Tobacco Shops",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 38.5968851,
      longitude: -121.4167039,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "2121 Arden Way",
      address2: "",
      address3: "",
      city: "Sacramento",
      zip_code: "95825",
      country: "US",
      state: "CA",
      display_address: ["2121 Arden Way", "Sacramento, CA 95825"],
    },
    phone: "+19169215328",
    display_phone: "(916) 921-5328",
    distance: 18342.305101615726,
  },
  {
    id: "4HP00RF9DzGSBBvl3ZhOtQ",
    alias: "lakeside-beverages-granite-bay",
    name: "Lakeside Beverages",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/jtH-CeyGlfxTam9dHnivzw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/lakeside-beverages-granite-bay?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 78,
    categories: [
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
      {
        alias: "wine_bars",
        title: "Wine Bars",
      },
      {
        alias: "beerbar",
        title: "Beer Bar",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.74286,
      longitude: -121.16803,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "7130 Douglas Blvd",
      address2: "",
      address3: "",
      city: "Granite Bay",
      zip_code: "95746",
      country: "US",
      state: "CA",
      display_address: ["7130 Douglas Blvd", "Granite Bay, CA 95746"],
    },
    phone: "+19167910684",
    display_phone: "(916) 791-0684",
    distance: 19264.308965329205,
  },
  {
    id: "iaYTyJYFT05YhDF7WqTqzA",
    alias: "la-riviera-market-and-spirits-sacramento",
    name: "La Riviera Market and Spirits",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/bphoto/lMt91hSmaZhXmbz56rtV_g/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/la-riviera-market-and-spirits-sacramento?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 28,
    categories: [
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
      {
        alias: "convenience",
        title: "Convenience Stores",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.5624939446672,
      longitude: -121.358688570225,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "9331 La Riviera Dr",
      address2: "",
      address3: "",
      city: "Sacramento",
      zip_code: "95826",
      country: "US",
      state: "CA",
      display_address: ["9331 La Riviera Dr", "Sacramento, CA 95826"],
    },
    phone: "+19163648701",
    display_phone: "(916) 364-8701",
    distance: 13142.746016678842,
  },
  {
    id: "J2_Czu3obuxrwJGjEOCAuA",
    alias: "red-rooster-burgers-and-brew-garden-valley",
    name: "Red Rooster Burgers & Brew",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/XIsOO3NlczecfMNV452qBw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/red-rooster-burgers-and-brew-garden-valley?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 71,
    categories: [
      {
        alias: "burgers",
        title: "Burgers",
      },
      {
        alias: "icecream",
        title: "Ice Cream & Frozen Yogurt",
      },
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 38.850351,
      longitude: -120.860547,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "5032 Garden Valley Rd",
      address2: "",
      address3: "",
      city: "Garden Valley",
      zip_code: "95633",
      country: "US",
      state: "CA",
      display_address: ["5032 Garden Valley Rd", "Garden Valley, CA 95633"],
    },
    phone: "+15303332400",
    display_phone: "(530) 333-2400",
    distance: 43186.574459242715,
  },
  {
    id: "mzFD5ikLseg8Xf31H9HUdg",
    alias: "total-wine-and-more-roseville",
    name: "Total Wine & More",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/Vl5iXMvhIuBeal5FUKepLw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/total-wine-and-more-roseville?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 201,
    categories: [
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
      {
        alias: "tobaccoshops",
        title: "Tobacco Shops",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 38.7816447,
      longitude: -121.2718453,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "5791 Five Star Blvd",
      address2: "",
      address3: "",
      city: "Roseville",
      zip_code: "95678",
      country: "US",
      state: "CA",
      display_address: ["5791 Five Star Blvd", "Roseville, CA 95678"],
    },
    phone: "+19167912488",
    display_phone: "(916) 791-2488",
    distance: 23929.912508733487,
  },
  {
    id: "ndOScVxIWCEYVQg9gCB8pg",
    alias: "sheldon-wine-shop-elk-grove",
    name: "Sheldon Wine Shop",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/ysJmio8W8JNem5mQQQB7Sw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/sheldon-wine-shop-elk-grove?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 14,
    categories: [
      {
        alias: "winetastingroom",
        title: "Wine Tasting Room",
      },
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
    ],
    rating: 5.0,
    coordinates: {
      latitude: 38.4383164100154,
      longitude: -121.396781355143,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "8361 Sheldon Rd",
      address2: "",
      address3: "",
      city: "Elk Grove",
      zip_code: "95624",
      country: "US",
      state: "CA",
      display_address: ["8361 Sheldon Rd", "Elk Grove, CA 95624"],
    },
    phone: "+19169703042",
    display_phone: "(916) 970-3042",
    distance: 22172.782321650542,
  },
  {
    id: "1G62hEJvpfWKWdcmbg9yqg",
    alias: "l-and-m-liquors-orangevale",
    name: "L & M Liquors",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/zK1kYoKVAI5V-GOm6hlLnw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/l-and-m-liquors-orangevale?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 45,
    categories: [
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.678217173544354,
      longitude: -121.2287877,
    },
    transactions: [],
    price: "$",
    location: {
      address1: "8836 Greenback Ln",
      address2: "",
      address3: "",
      city: "Orangevale",
      zip_code: "95662",
      country: "US",
      state: "CA",
      display_address: ["8836 Greenback Ln", "Orangevale, CA 95662"],
    },
    phone: "+19169888914",
    display_phone: "(916) 988-8914",
    distance: 11916.564397511425,
  },
  {
    id: "ijBFH2U-6Wh9CL_0Pg5RtQ",
    alias: "coloma-food-and-liquor-rancho-cordova",
    name: "Coloma Food & Liquor",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/WXhWB8Y0bZqlR3IjRG-b1w/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/coloma-food-and-liquor-rancho-cordova?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 21,
    categories: [
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
      {
        alias: "convenience",
        title: "Convenience Stores",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.6169281,
      longitude: -121.2729492,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "11082 Coloma Rd",
      address2: "Ste A1",
      address3: "",
      city: "Rancho Cordova",
      zip_code: "95670",
      country: "US",
      state: "CA",
      display_address: [
        "11082 Coloma Rd",
        "Ste A1",
        "Rancho Cordova, CA 95670",
      ],
    },
    phone: "+19166318043",
    display_phone: "(916) 631-8043",
    distance: 7510.793554101904,
  },
  {
    id: "vGKYdstCoSKDmthwW6_g2Q",
    alias: "good-bottle-shop-sacramento",
    name: "Good Bottle Shop",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/1NNzQsdQqoG_AXJrWuAcAQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/good-bottle-shop-sacramento?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 10,
    categories: [
      {
        alias: "beverage_stores",
        title: "Beverage Store",
      },
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
    ],
    rating: 5.0,
    coordinates: {
      latitude: 38.57808233,
      longitude: -121.4930565,
    },
    transactions: ["delivery", "pickup"],
    location: {
      address1: "1123 11th St",
      address2: "",
      address3: null,
      city: "Sacramento",
      zip_code: "95814",
      country: "US",
      state: "CA",
      display_address: ["1123 11th St", "Sacramento, CA 95814"],
    },
    phone: "+19163094868",
    display_phone: "(916) 309-4868",
    distance: 24785.313895732255,
  },
  {
    id: "SUj1Lr_igobzb7r7OO2xRQ",
    alias: "bourbons-and-more-roseville",
    name: "Bourbons & More",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/R4NPmI2_gOLxTpxIYG6iPw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/bourbons-and-more-roseville?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 39,
    categories: [
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.7449092753449,
      longitude: -121.264409239867,
    },
    transactions: [],
    location: {
      address1: "1611 Douglas Blvd",
      address2: "",
      address3: null,
      city: "Roseville",
      zip_code: "95661",
      country: "US",
      state: "CA",
      display_address: ["1611 Douglas Blvd", "Roseville, CA 95661"],
    },
    phone: "+19167493141",
    display_phone: "(916) 749-3141",
    distance: 19809.49709513363,
  },
  {
    id: "AlZ_anMPLXEN_fqX8zPWhg",
    alias: "shift-change-sacramento-2",
    name: "Shift Change",
    image_url:
      "https://s3-media3.fl.yelpcdn.com/bphoto/LlF61kPRkwX4fDgrbd5SjQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/shift-change-sacramento-2?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 28,
    categories: [
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
      {
        alias: "servicestations",
        title: "Gas Stations",
      },
      {
        alias: "convenience",
        title: "Convenience Stores",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.534106,
      longitude: -121.494529,
    },
    transactions: [],
    price: "$",
    location: {
      address1: "4516 Freeport Blvd",
      address2: "",
      address3: null,
      city: "Sacramento",
      zip_code: "95822",
      country: "US",
      state: "CA",
      display_address: ["4516 Freeport Blvd", "Sacramento, CA 95822"],
    },
    phone: "+19167318010",
    display_phone: "(916) 731-8010",
    distance: 25271.617685567257,
  },
  {
    id: "ztvUfjxzQsngJ5GFcxbJqA",
    alias: "lichines-liquor-and-deli-sacramento",
    name: "Lichine's Liquor & Deli",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/EGJAGITT1G5QLvBOJYoZQQ/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/lichines-liquor-and-deli-sacramento?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 23,
    categories: [
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.496673,
      longitude: -121.511162,
    },
    transactions: [],
    price: "$",
    location: {
      address1: "7107 S Land Park Dr",
      address2: "",
      address3: "",
      city: "Sacramento",
      zip_code: "95831",
      country: "US",
      state: "CA",
      display_address: ["7107 S Land Park Dr", "Sacramento, CA 95831"],
    },
    phone: "+19164226920",
    display_phone: "(916) 422-6920",
    distance: 27673.754412709695,
  },
  {
    id: "YaJCt85eIqoJY2b3DmcGXw",
    alias: "stonelake-vine-and-spirits-elk-grove",
    name: "Stonelake Vine & Spirits",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/a7-GEI-0G13rJ8FJfMAi3A/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/stonelake-vine-and-spirits-elk-grove?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 25,
    categories: [
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.4076830372213,
      longitude: -121.47810459137,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "2619 Riparian Dr",
      address2: "",
      address3: "Stonelake Landing",
      city: "Elk Grove",
      zip_code: "95757",
      country: "US",
      state: "CA",
      display_address: [
        "2619 Riparian Dr",
        "Stonelake Landing",
        "Elk Grove, CA 95757",
      ],
    },
    phone: "+19167144770",
    display_phone: "(916) 714-4770",
    distance: 29790.34623349265,
  },
  {
    id: "3CXFa-CMeNRTL1eBA3tZWw",
    alias: "curtis-park-market-sacramento",
    name: "Curtis Park Market",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/OSZTWGfsawIRvEyXXuk6fA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/curtis-park-market-sacramento?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 72,
    categories: [
      {
        alias: "grocery",
        title: "Grocery",
      },
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
    ],
    rating: 4.0,
    coordinates: {
      latitude: 38.554874420166,
      longitude: -121.483001708984,
    },
    transactions: ["delivery", "pickup"],
    price: "$$",
    location: {
      address1: "2703 24th St",
      address2: null,
      address3: "",
      city: "Sacramento",
      zip_code: "95818",
      country: "US",
      state: "CA",
      display_address: ["2703 24th St", "Sacramento, CA 95818"],
    },
    phone: "+19164566488",
    display_phone: "(916) 456-6488",
    distance: 23992.79369785668,
  },
  {
    id: "NSKq-3m7S64O_JxZ6yURGA",
    alias: "california-distilled-spirits-auburn-2",
    name: "California Distilled Spirits",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/OK38WQ7VE38xqkC3AOU4Rw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/california-distilled-spirits-auburn-2?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 9,
    categories: [
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
      {
        alias: "distilleries",
        title: "Distilleries",
      },
      {
        alias: "winetours",
        title: "Wine Tours",
      },
    ],
    rating: 5.0,
    coordinates: {
      latitude: 38.9906349182129,
      longitude: -121.114318847656,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "12205 Locksley Ln11",
      address2: null,
      address3: "",
      city: "Auburn",
      zip_code: "95602",
      country: "US",
      state: "CA",
      display_address: ["12205 Locksley Ln11", "Auburn, CA 95602"],
    },
    phone: "+19165996541",
    display_phone: "(916) 599-6541",
    distance: 43193.06073863171,
  },
  {
    id: "NkJBSooeJ6QUn3X0-sy7aQ",
    alias: "liquor-locker-roseville-3",
    name: "Liquor Locker",
    image_url:
      "https://s3-media2.fl.yelpcdn.com/bphoto/tYITghX86dGB8GxA98IHOw/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/liquor-locker-roseville-3?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 17,
    categories: [
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.7365,
      longitude: -121.28958,
    },
    transactions: ["delivery", "pickup"],
    price: "$$",
    location: {
      address1: "115 Darling Way",
      address2: "",
      address3: "",
      city: "Roseville",
      zip_code: "95678",
      country: "US",
      state: "CA",
      display_address: ["115 Darling Way", "Roseville, CA 95678"],
    },
    phone: "+19167554164",
    display_phone: "(916) 755-4164",
    distance: 19584.112328114512,
  },
  {
    id: "v04daQTleEyUFmZ7hkHVwQ",
    alias: "beyond-napa-wine-market-sacramento",
    name: "Beyond Napa Wine Market",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/bphoto/F_ywMfBY161u-HgH4Bb5FA/o.jpg",
    is_closed: false,
    url: "https://www.yelp.com/biz/beyond-napa-wine-market-sacramento?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    review_count: 31,
    categories: [
      {
        alias: "beer_and_wine",
        title: "Beer, Wine & Spirits",
      },
    ],
    rating: 4.5,
    coordinates: {
      latitude: 38.573783051518866,
      longitude: -121.40245998228814,
    },
    transactions: [],
    price: "$$",
    location: {
      address1: "2580 Fair Oaks Blvd",
      address2: "Ste 6",
      address3: "",
      city: "Sacramento",
      zip_code: "95825",
      country: "US",
      state: "CA",
      display_address: ["2580 Fair Oaks Blvd", "Ste 6", "Sacramento, CA 95825"],
    },
    phone: "+19164818665",
    display_phone: "(916) 481-8665",
    distance: 16902.606318877242,
  },
];
