export const eventsData = [
  {
    attending_count: 200,
    category: "food-and-drink",
    cost: null,
    cost_max: null,
    description:
      "Yelp Sacramento proudly presents our very own Sac Pizza Week, featuring nightly events and numerous check-in offers at highly-rated local pizza hot spots...",
    event_site_url:
      "https://www.yelp.com/events/sacramento-yelp-presents-sac-pizza-week?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_event_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    id: "sacramento-yelp-presents-sac-pizza-week",
    image_url:
      "https://s3-media1.fl.yelpcdn.com/ephoto/GwdONxKkgOkZjnpWPtkKcw/o.jpg",
    interested_count: 61,
    is_canceled: false,
    is_free: false,
    is_official: true,
    latitude: 38.5824933,
    longitude: -121.4941738,
    name: "Yelp Presents: Sac Pizza Week",
    tickets_url: null,
    time_end: "2019-06-16T22:00:00-07:00",
    time_start: "2019-06-10T10:00:00-07:00",
    location: {
      address1: "",
      address2: null,
      address3: "",
      city: "Sacramento",
      zip_code: "95814",
      country: "US",
      state: "CA",
      display_address: ["Sacramento, CA 95814"],
      cross_streets: "",
    },
    business_id: "city-of-sacramento-sacramento",
  },
  {
    attending_count: 1,
    category: "food-and-drink",
    cost: null,
    cost_max: null,
    description:
      "***RSVP NOW CLOSED FOR FREE BOBA. YOU CAN STILL VOTE STARTING MARCH 8 VIA INSTAGRAM @yelpsacramento***\n\nDid someone say free boba?? \n\nJoin Yelp Sacramento...",
    event_site_url:
      "https://www.yelp.com/events/sacramento-yelp-sacramentos-boba-bracket?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_event_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    id: "sacramento-yelp-sacramentos-boba-bracket",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/ephoto/J-ZwPsaTIeQLamLxCu2GGg/o.jpg",
    interested_count: 1066,
    is_canceled: false,
    is_free: false,
    is_official: true,
    latitude: 38.5824933,
    longitude: -121.4941738,
    name: "Yelp Sacramento's Boba Bracket",
    tickets_url: null,
    time_end: "2021-03-31T12:00:00-07:00",
    time_start: "2021-03-01T09:00:00-08:00",
    location: {
      address1: "",
      address2: null,
      address3: "",
      city: "Sacramento",
      zip_code: "95814",
      country: "US",
      state: "CA",
      display_address: ["Sacramento, CA 95814"],
      cross_streets: "",
    },
    business_id: "city-of-sacramento-sacramento",
  },
  {
    attending_count: 1,
    category: "food-and-drink",
    cost: null,
    cost_max: null,
    description:
      "*EVENT FULL. CLOSED TO NEW RSVPs.*\n\nIf complimentary wine tastings and discovering new, award-winning wineries near Sacramento are your thing, look no...",
    event_site_url:
      "https://www.yelp.com/events/west-sacramento-passport-to-yolo-wine-country?adjust_creative=BRwnxxQVDh4lnO7BFVYRrQ&utm_campaign=yelp_api_v3&utm_medium=api_v3_event_search&utm_source=BRwnxxQVDh4lnO7BFVYRrQ",
    id: "west-sacramento-passport-to-yolo-wine-country",
    image_url:
      "https://s3-media4.fl.yelpcdn.com/ephoto/H9hjosb2_kOLNEj8bxpJbg/o.jpg",
    interested_count: 446,
    is_canceled: false,
    is_free: false,
    is_official: true,
    latitude: 38.5876346,
    longitude: -121.5278856,
    name: "Passport to Yolo Wine Country",
    tickets_url: null,
    time_end: "2021-06-30T17:00:00-07:00",
    time_start: "2021-06-01T11:00:00-07:00",
    location: {
      address1: "",
      address2: "",
      address3: "",
      city: "West Sacramento",
      zip_code: "95605",
      country: "US",
      state: "CA",
      display_address: ["West Sacramento, CA 95605"],
      cross_streets: "",
    },
    business_id: "yolo-county-west-sacramento",
  },
];
